{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "crisismesh.fullname" . }}
spec:
  selector:
    matchLabels: { app.kubernetes.io/name: {{ include "crisismesh.name" . }} }
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}

